import type { Metadata } from "next";

import "../styles/globals.scss";
import Footer from "@/feature/homepage/component/footer";
import Navbar from "@/feature/homepage/component/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
